#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
#
# Parameters:
#	The path to the file to be transferred
#	The IP of the server we want to transfer the file to
#	The username scp connects with
#	The path to the SSH private key that scp uses
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	if [ $# -eq 3 ]
	then
		# No private key provided by user
		scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
	else
		# Private key provided
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
	fi
fi
