#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
sudo cp /etc/hosts /etc/hosts.old
sudo sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts.old
echo "8.8.8.8   facebook.com" >> /etc/hosts.old
sudo cp -f /etc/hosts.old /etc/hosts
